### ISSUE TITLE
docker run dead... hours waiting ¬¬ 

### ISSUE THREAD

**Issue by jujes** [reactioncommerce/reaction#1034]
### Climate code

```
$ uname -r
  3.13.0-86-generic
$ docker --version
   Docker version 1.11.1, build 5604cbe
```

### Expected behavior

```
=> Started your app.
=> App running at: http://demosite.dev
```

### Actual Behavior

```
21:50:17.690Z  INFO Reaction: Reaction initialization finished.
21:50:18.462Z  INFO Reaction: Modified 1 document while importing 1 to Shipping
```

### Steps to Reproduce the Behavior

```
git clone https://github.com/reactioncommerce/reaction.git
cd reaction
docker build -t demo/reaction .
docker run --rm  -p ::80 \
-e MONGO_URL="mongodb://rsoap_db:rsoap_db@jello.modulusmongo.net:27017/tar7Azyz" \
-e ROOT_URL="http://rootsoap.com" \
-e REACTION_EMAIL="hello@rootsoap.com" \
-e REACTION_USER="admin" \
-e REACTION_AUTH="sdfiddsky" \
-t demo/reaction
```

**Comment by jshimko** [comment]
Not sure if this has anything to do with your issue, but the last line in your `docker run` command shouldn't have `-t` before the container name.  The `-t` doesn't mean the same thing in `docker run` as it does in `docker build`.

Other than that, I can't replicate your issue.  I used Docker Compose to run a fresh Reaction build with Mongo in another container and the app worked as expected.

So, my reproduction steps...

```sh
docker build -t reaction-test .
```
Then create a `docker-compose.yml` in the root of the project:
```yaml
# this file will work as-is.  no need to edit it.

reaction:
  image: reaction-test
  links:
    - mongo
  ports:
    - "80:80"
  environment:
    ROOT_URL: "http://example.com"
    MONGO_URL: "mongodb://mongo:27017/meteor"

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
```
And finally, start it up...
```sh
docker-compose up -d
```
Optionally, view the Reaction logs after starting...
```sh
docker-compose logs -f reaction
```
When I do the exact steps above, it all works as expected.  If that works for you, I'd say the next step would be to change the `MONGO_URL` to your database and see if anything changes.

Also, note that our Docker deployment docs were recently rewritten with a lot more details for things like Docker Machine, etc.
See: https://docs.reactioncommerce.com/reaction-docs/master/deploying-reaction-using-docker
