### ISSUE TITLE
reaction behind proxy = 502 Bad Gateway

### ISSUE THREAD

**Issue by jujes** [reactioncommerce/reaction#1075]
#### Actual Behavior

**502 Bad Gateway --> nginx/1.9.15**

#### Steps to Reproduce the Behavior

**run nginx-proxy**

`docker run -d -p 80:80 -p 443:443 -v /etc/nginx/certs:/etc/nginx/certs -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy
`

**docker-compose.yml**

```
reaction:
  restart: always
  image: reactioncommerce/reaction
  links:
    - mongo.reaction
  container_name: reaction
  environment:
    - VIRTUAL_HOST=reaction.dev
    - ROOT_URL=http://reaction.dev
    - MONGO_URL=mongodb://mongo.reaction:27017/reaction
    - REACTION_EMAIL=admin@reaction.dev
    - REACTION_USER=admin
    - REACTION_AUTH=password
mongo.reaction:
  restart: always
  image: mongo:2.6.11
  command: mongod --smallfiles
  container_name: mongo.reaction

```

**docker-compose up -d**

[here logs for more info 46](https://github.com/meteorhacks/meteord/issues/46#issuecomment-225429896)
