### ISSUE TITLE
reaction-layout

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#148]
Here's some rough thoughts on a possible new layout approach:

Create a new "component" collection:
```
@ComponentSchema = new SimpleSchema
  name:
    type: String
  component:
    type: String
  helper:
    type: String
  template:
    type: String
  position:
    type: Object

@Components = new Meteor.Collection("Components",[ComponentSchema])
```

Components types are UI helpers, that dynamically load templates, perhaps setting data 

- Textarea
- Hero
- Product
- SocialBlock

This could allow for extending, customizing template (component) by cloning, changing the values of the components

You can have multiple templates for components

- Hero -> Large Slider
- Hero -> Static Text
- Hero -> my custom hero template

You add to any grid page by:

- Add new component
  - Choose Type
  - Choose template
  - Component Configuration Screen
  - Drag to position (and store position / priority)

For example:
Add a product 
  - add new product, goto current product entry screen
   -  grid settings
    -   configure tags to display in grid
    -   configure filters (gold, silver, new,etc)

Add a hero -> inline hero manager
  
The "productGrid" doesn't exist anymore, instead it's a generic layout grid, that injects the dynamic component templates into the grid

You wouldn't create a "productGrid" template, but you would loop through the applicable collection data and render each individual product grid item template and insert into a layout. You should be able to mix and match different components this way.

Is still a drag and drop interface, storing position or other layout in the component collection level.

I'm thinking that potentially the rendered layout would be a client layout collection + template
