### ISSUE TITLE
Traefik Proxy => language not work...

### ISSUE THREAD

**Issue by jujes** [reactioncommerce/reaction#2227]
### Expected behavior
use traefik proxy

### traefik.toml
```
defaultEntryPoints = ["http", "https"]

[web]

address = ":8080"

[entryPoints]
  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"
watch = true
exposedbydefault = false
```
### Dockerfile
```
FROM traefik:camembert
ADD traefik.toml .
EXPOSE 80
EXPOSE 8080
EXPOSE 443
```
### docker-compsoe .yml

```
version: '2'

services:
  traefik:
    container_name: traefik
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webgateway
    cap_drop:
      - all
    cap_add:
      - net_bind_service

networks:
  webgateway:
    driver: bridge
```
______
docker-compose up -d
______

### docker-compose.yml
```
version: '2'
services:
  local.dev:
    container_name: local.dev
    restart: always
    image: reactioncommerce/reaction:latest
    environment:
      ROOT_URL: "http://local.dev"
      MONGO_URL: "mongodb://mongo:27017/reaction"
      VIRTUAL_HOST: "www.local.dev,local.dev"
      REACTION_EMAIL: "admin@local.dev"
      REACTION_USER: "admin"
      REACTION_AUTH: "password"
    labels:
      - "traefik.frontend.entryPoints=http"
      - "traefik.protocol=http"
      - "traefik.port=3000"
      - "traefik.enable=true"
      - "traefik.backend=local.dev"
      - "traefik.frontend.rule=Host:local.dev, www.local.dev"
      - "traefik.docker.network=docker_webgateway"
      - "traefik.domain=local.dev"
    links:
      - mongo
    networks:
      - docker_webgateway

  mongo:
    container_name: db.local.dev
    restart: always
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    labels:
      - "traefik.enable=false"
    networks:
      - docker_webgateway

networks:
  docker_webgateway:
    external:
      name: docker_webgateway
```
______
docker-compose up -d
______
