### ISSUE TITLE
Only 10% of performance: how long take to show content and become usable?

### ISSUE THREAD

**Issue by roboto-cloud** [reactioncommerce/reaction#3220]
#### **only 10% of usability using google-chrome audits tests...**
![screenshot from 2017-11-01 20-19-44](https://user-images.githubusercontent.com/32390825/32293017-24886256-bf42-11e7-9fd7-a8ba94a5847f.png)

### Steps to reproduce the behavior
**hardware:** 300 GB 100% SSD + RAM 12 GB (guaranteed) + 100 Mbit/s port  + Four cores Intel® Xeon®

**software:** docker-compose.yml

```
version: "3"

networks:
  comp_proxy:
    external: true
  internal:
    external: false

services:
  reaction.dev:
    container_name: reaction.dev
    restart: always
    image: reactioncommerce/reaction:v1.5.5
    environment:
      ROOT_URL: "https://reaction.dev"
      MONGO_URL: "mongodb://mongo:27017/reaction"
      VIRTUAL_HOST: "reaction.dev"
      REACTION_EMAIL: "hello@reaction.dev"
      REACTION_USER: "admin"
      REACTION_AUTH: "password"
    labels:
      - "traefik.backend=reaction.dev"
      - "traefik.frontend.rule=Host:reaction.dev"
      - "traefik.docker.network=comp_proxy"
      - "traefik.port=3000"
    networks:
      - internal
      - comp_proxy
    links:
      - db.reaction.dev:mongo
    depends_on:
      - db.reaction.dev

  db.reaction.dev:
    container_name: db.reaction.dev
    restart: always
    image: mongo:latest
    command: mongod --smallfiles --oplogSize 128
    volumes:
      - ../live/db:/data/db
    labels:
      - "traefik.enable=false"
    networks:
      - internal


```
thanks in advance!

We're giving away t-shirts, tote bags, and $500 gift cards to **anyone who contributes** a feature or fixes a bug. Learn more about the [Reaction Hack-a-bug-a-thon](https://blog.reactioncommerce.com/introducing-the-reaction-hack-a-bug-a-thon/).
