### ISSUE TITLE
Docker and mongoDB auth security issue

### ISSUE THREAD

**Issue by raphaelluchini** [reactioncommerce/reaction#3985]
## Prerequisites
* [X] Are you running the latest version?
* [X] Are you able to consistently reproduce the issue?
* [X] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
First of all, I would like to say thank your for such a great tool you guys are developing!

This issue is not related with the framework itself. But is related of security of docker, more specific with mongoDB.

Reaction Docker images and docker compose file today (and the next version 1.9.0, i've checked the next release :P) don't use any type of authentication nor provide any documentation explaining how to set up it. If someone deploy it today on a server without a firewall for example, the database is exposed to the world without any password.

## Possible Solution
I suggest you guys enforce at least a default user and password for the database(maybe force a custom one) and provide a basic documentation explaining how to connect to mongo using the user credentials.

My solution was:

I had to create the users on my database manually and then use a custom docker compose configuration.

docker-compose.yml
```yml
  reaction:
    build: .
    restart: always
    depends_on:
      - mongo
    volumes:
      - reactiondata:/app
    ports:
      - "3000:3000"
    environment:
      ROOT_URL: "http://localhost"
      MONGO_URL: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}"

  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    command: mongod --storageEngine=wiredTiger --auth
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
  reactiondata:

```
### Versions
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.8.2
Reaction branch: master
Docker: 17.12.0-ce
